---

# REFS:
# http://www.aptly.info/doc/overview/
# http://www.unixmen.com/introducing-aptly-a-debian-repository-management-tool/

- debug:
    msg: |
      ***********************
      * aptly state=present *
      ***********************

- name: Aptly Debian repository key is present
  apt_key:
    keyserver: keys.gnupg.net
    id: E083A3782A194991
    state: present

- name: Aptly Debian repository is present
  apt_repository:
    repo: "deb http://repo.aptly.info/ squeeze main"
    state: present

- name: Aptly Debian package is present
  apt:
    name: aptly
    state: "{{ 'latest' if relkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Aptly user is present
  user:
    name: aptly
    state: present
    system: yes

- name: Aptly is configured
  copy:
    src: aptly.conf
    dest: /etc
    mode: "644"
    owner: root

- name: Aptly cache location is present
  file:
    path: /var/cache/aptly
    mode: "700"
    owner: aptly
    group: aptly
    state: directory

########
# data #
########

- name: Aptly repositories are assessed
  sudo: yes
  sudo_user: aptly
  command: aptly repo list
  register: cmd
  changed_when: no

- name: Aptly repositories are traced
  debug:
    var: cmd.stdout_lines

- name: Testing repository is present
  with_items: aptly_repositories
  when: "'[{{ item.name }}]' not in cmd.stdout"
  sudo: yes
  sudo_user: aptly
  command: "aptly repo create {{ item.name }}"


- name: Aptly published repositories are assessed
  command: aptly publish list
  register: cmd
  changed_when: no

- name: Aptly published repositories are traced
  debug:
    var: cmd.stdout_lines

- name: Testing repository is published
  with_items: relkit_aptly_repositories
  when: "'./{{ item.distribution }}' not in cmd.stdout"
  sudo: yes
  sudo_user: aptly
  command: "aptly publish repo -distribution={{ item.distribution }} -architectures=all,source,x86,amd64 -skip-signing=true {{ item.name }}"

###########
# service #
###########

- name: Aptly poorman service manifest is present
  when: relkit_aptly_autostart
  template:
    src: service_aptly.sh.j2
    dest: /usr/local/bin/service_aptly.sh
    owner: root
    group: staff
    mode: "755"

- name: Aptly service is started
  when: relkit_aptly_autostart
  command: service_aptly.sh start

