---

- name: present | Git package is present
  apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: present | Git user is present
  user:
    name: git
    shell: /usr/bin/git-shell
    system: no

- name: present | Git bare repositories are absent
  command: rm -rf /home/git/{{ item.name }}.git
  when: item.state == "absent"
  with_items: relkit_gitd_repositories

- name: present | Git bare repositories are present
  file:
    group: git
    name: /home/git/{{ item.name }}.git
    owner: git
    state: directory
  when: item.state == "present"
  with_items: relkit_gitd_repositories

- name: present | Git bare repositories are initialized
  shell: git init --bare chdir=/home/git/{{ item.name }}.git
  sudo: git
  when: item.state == "present"
  with_items: relkit_gitd_repositories

- name: present | Git service
  debug:
    msg: |
      Gitd does not come with a service manifest, use a 3rd-party role to generate one.
      To start the service manually, run:
      $ sudo -u git /usr/bin/git daemon --enable=upload-archive --export-all --syslog --user=git --group=git --reuseaddr --base-path=/home/git/ /home/git/
