---

- debug:
    msg: |
      ************************
      * jenkins state=absent *
      ************************

- name: Jenkins service is stopped

  service:
    name: jenkins
    state: stopped

- name: Jenkins Debian package is absent
  apt:
    name: jenkins
    state: absent

- name: Additional facts are computed
  set_fact:
    relkit_jenkins_url: "http://pkg.jenkins-ci.org/{{ 'debian-stable' if relkit_jenkins_stable else 'debian' }}"

- name: Jenkins debian repository is absent
  apt_repository:
    repo: "deb {{ relkit_jenkins_url }} binary/"
    state: absent

- name: Jenkins-ci Debian repository key is absent
  apt_key:
    url: "{{ relkit_jenkins_url }}/jenkins-ci.org.key"
    state: absent