---

- name: JRE7 package is present
  apt:
    name: openjdk-7-jre-headless
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Additional facts are computed
  set_fact:
    jenkins_url: "http://pkg.jenkins-ci.org/{{ 'debian-stable' if relkit_jenkins_stable else 'debian' }}"

- name: Jenkins-ci debian repository key is present
  apt_key:
    id: "D50582E6"
    url: "{{ jenkins_url }}/jenkins-ci.org.key"
    state: present
  environment: "{{ relkit_environment }}"

- name: Jenkins debian repository is present
  apt_repository:
    repo: "deb {{ jenkins_url }} binary/"
    state: present
    update_cache: yes

- name: Jenkins package is present
  apt:
    name: jenkins
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Jenkins is configured
  template:
    src: jenkins-settings.j2
    dest: /etc/default/jenkins
    owner: root
    mode: "644"
  notify:
  - relkit_restart_jenkins

- name: Jenkins service is started
  service:
    name: jenkins
    state: started
    enabled: yes
