---

- debug:
    msg: |
      *************************
      * jenkins state=present *
      *************************

- name: JRE7 Debian package is present
  apt:
    name: openjdk-7-jre-headless
    state: "{{ 'latest' if relkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Additional facts are computed
  set_fact:
    jenkins_url: "http://pkg.jenkins-ci.org/{{ 'debian-stable' if relkit_jenkins_stable else 'debian' }}"

- name: Jenkins-ci Debian repository key is present
  apt_key:
    id: "D50582E6"
    url: "{{ jenkins_url }}/jenkins-ci.org.key"
    state: present
  environment: "{{ relkit_environment }}"

- name: Jenkins Debian repository is present
  apt_repository:
    repo: "deb {{ jenkins_url }} binary/"
    state: present
    update_cache: yes

- name: Jenkins Debian package is present
  apt:
    name: jenkins
    state: "{{ 'latest' if relkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Jenkins is configured
  template:
    src: default.jenkins.j2
    dest: /etc/default/jenkins
    owner: root
    mode: "644"
  notify:
  - relkit_restart_jenkins

- name: Jenkins service is started
  when: relkit_jenkins_autostart
  service:
    name: jenkins
    state: started
    enabled: yes
