---
- fail:
    msg: unsupported platform -- please contact the role maintainer for support
  name: Assert the target platform is supported
  when: ansible_distribution not in ['Ubuntu', 'Debian']
- include: aptly_present.yml
  name: Taskfile aptly_present.yml is included
  when: relkit_aptly_state == "present"
- include: jenkins_absent.yml
  name: Taskfile jenkins_absent.yml is included
  when: relkit_jenkins_state == "absent"
- include: jenkins_present.yml
  name: Taskfile jenkins_present.yml is included
  when: relkit_jenkins_state == "present"
