---

- name: present | Pip Debian package is present
  apt:
    name: python-pip
    state: "{{ 'latest' if relkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600

- name: present | Support Python packages are present
  with_items:
  - pypiserver
  - passlib
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "{{ '--upgrade' if relkit_update else '' }}"

- name: present | PyPI server user is present
  user:
    name: pypiserver
    state: present
    system: yes

- name: present | PyPI server cache directory is present
  file:
    name: /var/cache/pypiserver
    state: directory
    owner: pypiserver
    group: pypiserver
    mode: "700"

- name: present | PyPI server configuration directory is present
  file:
    name: /etc/pypiserver
    state: directory
    owner: pypiserver
    group: pypiserver
    mode: "700"

- name: present | PyPI server htaccess is present
  copy:
    content: ""
    dest: /etc/pypiserver/htaccess
    owner: pypiserver
    group: pypiserver
    mode: "600"

- name: present | PyPI server accounts are present/absent
  with_items: relkit_pypiserver_users
  htpasswd:
    path: /etc/pypiserver/
    user: "{{ item.name }}"
    password: "{{ item.pass }}"
    state: "{{ item.state }}"
    crypt_scheme: md5_crypt
  notify:
  - relkit_restart_pypiserver

- name: present | PyPI server poorman service manifest is present
  when: relkit_pypiserver_autostart
  template:
    src: service_pypiserver.sh.j2
    dest: /usr/local/bin/service_pypiserver.sh
    owner: root
    group: staff
    mode: "755"

- name: present | PyPI server service is started
  when: relkit_pypiserver_autostart
  command: service_pypiserver.sh start status
